octomap_frame: ur_dual_I_base_link
octomap_resolution: 0.05
max_range: 1.25

sensors:
  - oak_depth_image

oak_depth_image:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /oak_cam/oak/stereo/image_raw_filtered
  queue_size: 20
  near_clipping_plane_distance: 0.20
  far_clipping_plane_distance: 1.25
  shadow_threshold: 0.2
  padding_scale: 2.0
  padding_offset: 0.03
  max_update_rate: 2.0
  filtered_cloud_topic: filtered_cloud
