octomap_frame: ur_dual_I_base_link
octomap_resolution: 0.05
max_range: 1.25

sensors:
  - cropped_obstacle_cloud

cropped_obstacle_cloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /ur_dual/cropped_obstacle_cloud
  max_range: 1.25
  point_subsample: 1
  padding_scale: 1.5
  padding_offset: 0.02
  max_update_rate: 5.0
  filtered_cloud_topic: filtered_cloud